using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NRakeCore.StopWordFilters
{
    /// <summary>
    /// English stop word list from http://members.unine.ch/jacques.savoy/clef/englishST.txt
    /// </summary>
    public class EnglishSmartStopWordFilter : BasicStopWordFilter
    {
        public override bool IsStopWord(string word)
        {
            if (word.Length < 3) { return true; }

            bool isStopWord = false;

            //Would it be faster to do a binary search here? I think flow control through a switch is O(1), whereas a binary search is O(log n).
            switch (word)
            {
                case "a":
                case "a's":
                case "able":
                case "about":
                case "above":
                case "according":
                case "accordingly":
                case "across":
                case "actually":
                case "after":
                case "afterwards":
                case "again":
                case "against":
                case "ain't":
                case "all":
                case "allow":
                case "allows":
                case "almost":
                case "alone":
                case "along":
                case "already":
                case "also":
                case "although":
                case "always":
                case "am":
                case "among":
                case "amongst":
                case "an":
                case "and":
                case "another":
                case "any":
                case "anybody":
                case "anyhow":
                case "anyone":
                case "anything":
                case "anyway":
                case "anyways":
                case "anywhere":
                case "apart":
                case "appear":
                case "appreciate":
                case "appropriate":
                case "are":
                case "aren't":
                case "around":
                case "as":
                case "aside":
                case "ask":
                case "asking":
                case "associated":
                case "at":
                case "available":
                case "away":
                case "awfully":
                case "b":
                case "be":
                case "became":
                case "because":
                case "become":
                case "becomes":
                case "becoming":
                case "been":
                case "before":
                case "beforehand":
                case "behind":
                case "being":
                case "believe":
                case "below":
                case "beside":
                case "besides":
                case "best":
                case "better":
                case "between":
                case "beyond":
                case "both":
                case "brief":
                case "but":
                case "by":
                case "c":
                case "c'mon":
                case "c's":
                case "came":
                case "can":
                case "can't":
                case "cannot":
                case "cant":
                case "cause":
                case "causes":
                case "certain":
                case "certainly":
                case "changes":
                case "clearly":
                case "co":
                case "com":
                case "come":
                case "comes":
                case "concerning":
                case "consequently":
                case "consider":
                case "considering":
                case "contain":
                case "containing":
                case "contains":
                case "corresponding":
                case "could":
                case "couldn't":
                case "course":
                case "currently":
                case "d":
                case "definitely":
                case "described":
                case "despite":
                case "did":
                case "didn't":
                case "different":
                case "do":
                case "does":
                case "doesn't":
                case "doing":
                case "don't":
                case "done":
                case "down":
                case "downwards":
                case "during":
                case "e":
                case "each":
                case "edu":
                case "eg":
                case "eight":
                case "either":
                case "else":
                case "elsewhere":
                case "enough":
                case "entirely":
                case "especially":
                case "et":
                case "etc":
                case "even":
                case "ever":
                case "every":
                case "everybody":
                case "everyone":
                case "everything":
                case "everywhere":
                case "ex":
                case "exactly":
                case "example":
                case "except":
                case "f":
                case "far":
                case "few":
                case "fifth":
                case "first":
                case "five":
                case "followed":
                case "following":
                case "follows":
                case "for":
                case "former":
                case "formerly":
                case "forth":
                case "four":
                case "from":
                case "further":
                case "furthermore":
                case "g":
                case "get":
                case "gets":
                case "getting":
                case "given":
                case "gives":
                case "go":
                case "goes":
                case "going":
                case "gone":
                case "got":
                case "gotten":
                case "greetings":
                case "h":
                case "had":
                case "hadn't":
                case "happens":
                case "hardly":
                case "has":
                case "hasn't":
                case "have":
                case "haven't":
                case "having":
                case "he":
                case "he's":
                case "hello":
                case "help":
                case "hence":
                case "her":
                case "here":
                case "here's":
                case "hereafter":
                case "hereby":
                case "herein":
                case "hereupon":
                case "hers":
                case "herself":
                case "hi":
                case "him":
                case "himself":
                case "his":
                case "hither":
                case "hopefully":
                case "how":
                case "howbeit":
                case "however":
                case "i":
                case "i'd":
                case "i'll":
                case "i'm":
                case "i've":
                case "ie":
                case "if":
                case "ignored":
                case "immediate":
                case "in":
                case "inasmuch":
                case "inc":
                case "indeed":
                case "indicate":
                case "indicated":
                case "indicates":
                case "inner":
                case "insofar":
                case "instead":
                case "into":
                case "inward":
                case "is":
                case "isn't":
                case "it":
                case "it'd":
                case "it'll":
                case "it's":
                case "its":
                case "itself":
                case "j":
                case "just":
                case "k":
                case "keep":
                case "keeps":
                case "kept":
                case "know":
                case "knows":
                case "known":
                case "l":
                case "last":
                case "lately":
                case "later":
                case "latter":
                case "latterly":
                case "least":
                case "less":
                case "lest":
                case "let":
                case "let's":
                case "like":
                case "liked":
                case "likely":
                case "little":
                case "look":
                case "looking":
                case "looks":
                case "ltd":
                case "m":
                case "mainly":
                case "many":
                case "may":
                case "maybe":
                case "me":
                case "mean":
                case "meanwhile":
                case "merely":
                case "might":
                case "more":
                case "moreover":
                case "most":
                case "mostly":
                case "much":
                case "must":
                case "my":
                case "myself":
                case "n":
                case "name":
                case "namely":
                case "nd":
                case "near":
                case "nearly":
                case "necessary":
                case "need":
                case "needs":
                case "neither":
                case "never":
                case "nevertheless":
                case "new":
                case "next":
                case "nine":
                case "no":
                case "nobody":
                case "non":
                case "none":
                case "noone":
                case "nor":
                case "normally":
                case "not":
                case "nothing":
                case "novel":
                case "now":
                case "nowhere":
                case "o":
                case "obviously":
                case "of":
                case "off":
                case "often":
                case "oh":
                case "ok":
                case "okay":
                case "old":
                case "on":
                case "once":
                case "one":
                case "ones":
                case "only":
                case "onto":
                case "or":
                case "other":
                case "others":
                case "otherwise":
                case "ought":
                case "our":
                case "ours":
                case "ourselves":
                case "out":
                case "outside":
                case "over":
                case "overall":
                case "own":
                case "p":
                case "particular":
                case "particularly":
                case "per":
                case "perhaps":
                case "placed":
                case "please":
                case "plus":
                case "possible":
                case "presumably":
                case "probably":
                case "provides":
                case "q":
                case "que":
                case "quite":
                case "qv":
                case "r":
                case "rather":
                case "rd":
                case "re":
                case "really":
                case "reasonably":
                case "regarding":
                case "regardless":
                case "regards":
                case "relatively":
                case "respectively":
                case "right":
                case "s":
                case "said":
                case "same":
                case "saw":
                case "say":
                case "saying":
                case "says":
                case "second":
                case "secondly":
                case "see":
                case "seeing":
                case "seem":
                case "seemed":
                case "seeming":
                case "seems":
                case "seen":
                case "self":
                case "selves":
                case "sensible":
                case "sent":
                case "serious":
                case "seriously":
                case "seven":
                case "several":
                case "shall":
                case "she":
                case "should":
                case "shouldn't":
                case "since":
                case "six":
                case "so":
                case "some":
                case "somebody":
                case "somehow":
                case "someone":
                case "something":
                case "sometime":
                case "sometimes":
                case "somewhat":
                case "somewhere":
                case "soon":
                case "sorry":
                case "specified":
                case "specify":
                case "specifying":
                case "still":
                case "sub":
                case "such":
                case "sup":
                case "sure":
                case "t":
                case "t's":
                case "take":
                case "taken":
                case "tell":
                case "tends":
                case "th":
                case "than":
                case "thank":
                case "thanks":
                case "thanx":
                case "that":
                case "that's":
                case "thats":
                case "the":
                case "their":
                case "theirs":
                case "them":
                case "themselves":
                case "then":
                case "thence":
                case "there":
                case "there's":
                case "thereafter":
                case "thereby":
                case "therefore":
                case "therein":
                case "theres":
                case "thereupon":
                case "these":
                case "they":
                case "they'd":
                case "they'll":
                case "they're":
                case "they've":
                case "think":
                case "third":
                case "this":
                case "thorough":
                case "thoroughly":
                case "those":
                case "though":
                case "three":
                case "through":
                case "throughout":
                case "thru":
                case "thus":
                case "to":
                case "together":
                case "too":
                case "took":
                case "toward":
                case "towards":
                case "tried":
                case "tries":
                case "truly":
                case "try":
                case "trying":
                case "twice":
                case "two":
                case "u":
                case "un":
                case "under":
                case "unfortunately":
                case "unless":
                case "unlikely":
                case "until":
                case "unto":
                case "up":
                case "upon":
                case "us":
                case "use":
                case "used":
                case "useful":
                case "uses":
                case "using":
                case "usually":
                case "uucp":
                case "v":
                case "value":
                case "various":
                case "very":
                case "via":
                case "viz":
                case "vs":
                case "w":
                case "want":
                case "wants":
                case "was":
                case "wasn't":
                case "way":
                case "we":
                case "we'd":
                case "we'll":
                case "we're":
                case "we've":
                case "welcome":
                case "well":
                case "went":
                case "were":
                case "weren't":
                case "what":
                case "what's":
                case "whatever":
                case "when":
                case "whence":
                case "whenever":
                case "where":
                case "where's":
                case "whereafter":
                case "whereas":
                case "whereby":
                case "wherein":
                case "whereupon":
                case "wherever":
                case "whether":
                case "which":
                case "while":
                case "whither":
                case "who":
                case "who's":
                case "whoever":
                case "whole":
                case "whom":
                case "whose":
                case "why":
                case "will":
                case "willing":
                case "wish":
                case "with":
                case "within":
                case "without":
                case "won't":
                case "wonder":
                case "would":
                case "wouldn't":
                case "x":
                case "y":
                case "yes":
                case "yet":
                case "you":
                case "you'd":
                case "you'll":
                case "you're":
                case "you've":
                case "your":
                case "yours":
                case "yourself":
                case "yourselves":
                case "z":
                case "zero":
                    isStopWord = true;
                    break;
            }

            return isStopWord;
        }
    }
}
