using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NRakeCore.StopWordFilters
{
    /// <summary>
    /// French stop-word filter based on the list at http://members.unine.ch/jacques.savoy/clef/frenchST.txt
    /// </summary>
    public class FrenchStopWordFilter : BasicStopWordFilter
    {
        public override bool IsStopWord(string word)
        {
            if (word.Length < 3) { return true; }

            bool isStopWord = false;

            //Would it be faster to do a binary search here? I think flow control through a switch is O(1), whereas a binary search is O(log n).
            switch (word)
            {
                case "a":
                case "à":
                case "â":
                case "abord":
                case "afin":
                case "ah":
                case "ai":
                case "aie":
                case "ainsi":
                case "allaient":
                case "allo":
                case "allô":
                case "allons":
                case "après":
                case "assez":
                case "attendu":
                case "au":
                case "aucun":
                case "aucune":
                case "aujourd":
                case "aujourd'hui":
                case "auquel":
                case "aura":
                case "auront":
                case "aussi":
                case "autre":
                case "autres":
                case "aux":
                case "auxquelles":
                case "auxquels":
                case "avaient":
                case "avais":
                case "avait":
                case "avant":
                case "avec":
                case "avoir":
                case "ayant":
                case "b":
                case "bah":
                case "beaucoup":
                case "bien":
                case "bigre":
                case "boum":
                case "bravo":
                case "brrr":
                case "c":
                case "ça":
                case "car":
                case "ce":
                case "ceci":
                case "cela":
                case "celle":
                case "celle-ci":
                case "celle-là":
                case "celles":
                case "celles-ci":
                case "celles-là":
                case "celui":
                case "celui-ci":
                case "celui-là":
                case "cent":
                case "cependant":
                case "certain":
                case "certaine":
                case "certaines":
                case "certains":
                case "certes":
                case "ces":
                case "cet":
                case "cette":
                case "ceux":
                case "ceux-ci":
                case "ceux-là":
                case "chacun":
                case "chaque":
                case "cher":
                case "chère":
                case "chères":
                case "chers":
                case "chez":
                case "chiche":
                case "chut":
                case "ci":
                case "cinq":
                case "cinquantaine":
                case "cinquante":
                case "cinquantième":
                case "cinquième":
                case "clac":
                case "clic":
                case "combien":
                case "comme":
                case "comment":
                case "compris":
                case "concernant":
                case "contre":
                case "couic":
                case "crac":
                case "d":
                case "da":
                case "dans":
                case "de":
                case "debout":
                case "dedans":
                case "dehors":
                case "delà":
                case "depuis":
                case "derrière":
                case "des":
                case "dès":
                case "désormais":
                case "desquelles":
                case "desquels":
                case "dessous":
                case "dessus":
                case "deux":
                case "deuxième":
                case "deuxièmement":
                case "devant":
                case "devers":
                case "devra":
                case "différent":
                case "différente":
                case "différentes":
                case "différents":
                case "dire":
                case "divers":
                case "diverse":
                case "diverses":
                case "dix":
                case "dix-huit":
                case "dixième":
                case "dix-neuf":
                case "dix-sept":
                case "doit":
                case "doivent":
                case "donc":
                case "dont":
                case "douze":
                case "douzième":
                case "dring":
                case "du":
                case "duquel":
                case "durant":
                case "e":
                case "effet":
                case "eh":
                case "elle":
                case "elle-même":
                case "elles":
                case "elles-mêmes":
                case "en":
                case "encore":
                case "entre":
                case "envers":
                case "environ":
                case "es":
                case "ès":
                case "est":
                case "et":
                case "etant":
                case "étaient":
                case "étais":
                case "était":
                case "étant":
                case "etc":
                case "été":
                case "etre":
                case "être":
                case "eu":
                case "euh":
                case "eux":
                case "eux-mêmes":
                case "excepté":
                case "f":
                case "façon":
                case "fais":
                case "faisaient":
                case "faisant":
                case "fait":
                case "feront":
                case "fi":
                case "flac":
                case "floc":
                case "font":
                case "g":
                case "gens":
                case "h":
                case "ha":
                case "hé":
                case "hein":
                case "hélas":
                case "hem":
                case "hep":
                case "hi":
                case "ho":
                case "holà":
                case "hop":
                case "hormis":
                case "hors":
                case "hou":
                case "houp":
                case "hue":
                case "hui":
                case "huit":
                case "huitième":
                case "hum":
                case "hurrah":
                case "i":
                case "il":
                case "ils":
                case "importe":
                case "j":
                case "je":
                case "jusqu":
                case "jusque":
                case "k":
                case "l":
                case "la":
                case "là":
                case "laquelle":
                case "las":
                case "le":
                case "lequel":
                case "les":
                case "lès":
                case "lesquelles":
                case "lesquels":
                case "leur":
                case "leurs":
                case "longtemps":
                case "lorsque":
                case "lui":
                case "lui-même":
                case "m":
                case "ma":
                case "maint":
                case "mais":
                case "malgré":
                case "me":
                case "même":
                case "mêmes":
                case "merci":
                case "mes":
                case "mien":
                case "mienne":
                case "miennes":
                case "miens":
                case "mille":
                case "mince":
                case "moi":
                case "moi-même":
                case "moins":
                case "mon":
                case "moyennant":
                case "n":
                case "na":
                case "ne":
                case "néanmoins":
                case "neuf":
                case "neuvième":
                case "ni":
                case "nombreuses":
                case "nombreux":
                case "non":
                case "nos":
                case "notre":
                case "nôtre":
                case "nôtres":
                case "nous":
                case "nous-mêmes":
                case "nul":
                case "o":
                case "o|":
                case "ô":
                case "oh":
                case "ohé":
                case "olé":
                case "ollé":
                case "on":
                case "ont":
                case "onze":
                case "onzième":
                case "ore":
                case "ou":
                case "où":
                case "ouf":
                case "ouias":
                case "oust":
                case "ouste":
                case "outre":
                case "p":
                case "paf":
                case "pan":
                case "par":
                case "parmi":
                case "partant":
                case "particulier":
                case "particulière":
                case "particulièrement":
                case "pas":
                case "passé":
                case "pendant":
                case "personne":
                case "peu":
                case "peut":
                case "peuvent":
                case "peux":
                case "pff":
                case "pfft":
                case "pfut":
                case "pif":
                case "plein":
                case "plouf":
                case "plus":
                case "plusieurs":
                case "plutôt":
                case "pouah":
                case "pour":
                case "pourquoi":
                case "premier":
                case "première":
                case "premièrement":
                case "près":
                case "proche":
                case "psitt":
                case "puisque":
                case "q":
                case "qu":
                case "quand":
                case "quant":
                case "quanta":
                case "quant-à-soi":
                case "quarante":
                case "quatorze":
                case "quatre":
                case "quatre-vingt":
                case "quatrième":
                case "quatrièmement":
                case "que":
                case "quel":
                case "quelconque":
                case "quelle":
                case "quelles":
                case "quelque":
                case "quelques":
                case "quelqu'un":
                case "quels":
                case "qui":
                case "quiconque":
                case "quinze":
                case "quoi":
                case "quoique":
                case "r":
                case "revoici":
                case "revoilà":
                case "rien":
                case "s":
                case "sa":
                case "sacrebleu":
                case "sans":
                case "sapristi":
                case "sauf":
                case "se":
                case "seize":
                case "selon":
                case "sept":
                case "septième":
                case "sera":
                case "seront":
                case "ses":
                case "si":
                case "sien":
                case "sienne":
                case "siennes":
                case "siens":
                case "sinon":
                case "six":
                case "sixième":
                case "soi":
                case "soi-même":
                case "soit":
                case "soixante":
                case "son":
                case "sont":
                case "sous":
                case "stop":
                case "suis":
                case "suivant":
                case "sur":
                case "surtout":
                case "t":
                case "ta":
                case "tac":
                case "tant":
                case "te":
                case "té":
                case "tel":
                case "telle":
                case "tellement":
                case "telles":
                case "tels":
                case "tenant":
                case "tes":
                case "tic":
                case "tien":
                case "tienne":
                case "tiennes":
                case "tiens":
                case "toc":
                case "toi":
                case "toi-même":
                case "ton":
                case "touchant":
                case "toujours":
                case "tous":
                case "tout":
                case "toute":
                case "toutes":
                case "treize":
                case "trente":
                case "très":
                case "trois":
                case "troisième":
                case "troisièmement":
                case "trop":
                case "tsoin":
                case "tsouin":
                case "tu":
                case "u":
                case "un":
                case "une":
                case "unes":
                case "uns":
                case "v":
                case "va":
                case "vais":
                case "vas":
                case "vé":
                case "vers":
                case "via":
                case "vif":
                case "vifs":
                case "vingt":
                case "vivat":
                case "vive":
                case "vives":
                case "vlan":
                case "voici":
                case "voilà":
                case "vont":
                case "vos":
                case "votre":
                case "vôtre":
                case "vôtres":
                case "vous":
                case "vous-mêmes":
                case "vu":
                case "w":
                case "x":
                case "y":
                case "z":
                case "zut":
                    isStopWord = true;
                    break;
            }

            return isStopWord;
        }
    }
}
